package com.appbaba.iz.eum;

/**
 * Created by ChanZeeBm on 2015/12/26.
 */
public enum NetworkParams {
    CUPCAKE, DONUT, FROYO, GINGERBREAD, HONEYCOMB, ICECREAMSANDWICH,LOLLIPOP,SELLERLIST,BRANDIN,COLLECTION,
    CHECKPHONE,SENDMSG,REGISTER,LOGIN,INDEX,SUBJECT,SUBJECTDETAIL,ADDCUSTOMER,ARTICLECATE,ARTICLE,CUSTOMERLIST,
    CUSTOMERSAVE,CUSTOMERDEL,CHANGEPWD,FEEDBACK,LOGOUT,FOUNDPASSWORD,CHECKPHONEINUSE,CHANGEHEAD,CHANGEPERSON,CUSTOMERCOLLECTION
}
